[package]
name = "katnip"
description = "Katnip - a Hyprland-inspired Wayland compositor written in Rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "katnip"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
fontdue.workspace = true
bitflags.workspace = true
katnip-backend = { path = "../katnip-backend" }
katnip-config = { path = "../katnip-config" }
katnip-core = { path = "../katnip-core" }
katnip-plugins = { path = "../katnip-plugins" }
smithay.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
xkbcommon.workspace = true

[lints]
workspace = true
